// File: inc_rom_size.v
// Generated by MyHDL 0.11.43
// Date: Thu Dec 21 05:54:12 2023


`timescale 1ns/10ps

module inc_rom_size (
    addrrom_size,
    clk,
    host_intf_rst_i,
    addr,
    dout,
    data,
    wr,
    host_intf_done_o,
    addrrom
);
// Incrementer with enable.
// 
// count -- output
// enable -- control input, increment when 1
// clock -- clock input
// reset -- asynchronous reset input

output [11:0] addrrom_size;
reg [11:0] addrrom_size;
input clk;
input host_intf_rst_i;
output [23:0] addr;
reg [23:0] addr;
input [15:0] dout;
output [15:0] data;
reg [15:0] data;
output wr;
reg wr;
input host_intf_done_o;
output [11:0] addrrom;
reg [11:0] addrrom;




always @(posedge clk, posedge host_intf_rst_i) begin: INC_ROM_SIZE_SEQ
    if (host_intf_rst_i == 1) begin
        wr <= 0;
        data <= 0;
        addrrom <= 0;
        addr <= 0;
        addrrom_size <= 0;
    end
    else begin
        if ((host_intf_rst_i == 1)) begin
            addrrom_size <= 0;
        end
        if ((host_intf_done_o == 0)) begin
            wr <= 1;
            if ((addrrom_size <= 4095)) begin
                addrrom_size <= (addrrom_size + 1);
            end
            else begin
                addrrom_size <= 0;
            end
        end
        if ((host_intf_done_o == 1)) begin
            wr <= 0;
        end
		/* verilator lint_off WIDTHEXPAND */
        addr <= addrrom_size;
		/* verilator lint_off WIDTHEXPAND */
        addrrom <= addrrom_size;
        data <= dout;
    end
end

endmodule

