// File: jpeg.v
// Generated by MyHDL 0.11.43
// Date: Fri Jan 26 17:36:41 2024


`timescale 1ns/10ps

module jpeg (
    clk,
    l_s,
    r_s,
    s_s,
    res_s,
    lohipass,
    fwd_inv,
    ex
);


input clk;
input signed [15:0] l_s;
input signed [15:0] r_s;
input signed [15:0] s_s;
output signed [15:0] res_s;
reg signed [15:0] res_s;
input lohipass;
input fwd_inv;
input ex;



// lohipass 1 lo 0 hi pass filter
// fwd_inv 1 fwd 0 inv
always @(posedge clk) begin: JPEG_JPEG_HDL
    if (ex) begin
        if (lohipass) begin
            if (fwd_inv) begin
                res_s <= (s_s - ($signed(l_s >>> 1) + $signed(r_s >>> 1)));
            end
            else begin
                res_s <= (s_s + ($signed(l_s >>> 1) + $signed(r_s >>> 1)));
            end
        end
        else begin
            if (fwd_inv) begin
				/* verilator lint_off WIDTHEXPAND */
				/* verilator lint_off WIDTHTRUNC */
                res_s <= (s_s + $signed(((l_s + r_s) + 2) >>> 2));
				/* verilator lint_off WIDTHTRUNC */
				/* verilator lint_off WIDTHEXPAND */
            end
            else begin
                res_s <= (s_s - $signed(((l_s + r_s) + 2) >>> 2));
            end
        end
    end
end

endmodule
